version: '3.8'

services:
  proyecto-algoritmos:
    build: .
    ports:
      - "8080:8080"
    volumes:
      - ./data:/app/data
      - ./logs:/app/logs
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - JAVA_OPTS=-Xmx1g -Xms512m
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/proyecto-algoritmos/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  # Para futuras integraciones (base de datos, etc.)
  # postgres:
  #   image: postgres:15
  #   environment:
  #     POSTGRES_DB: algoritmos_db
  #     POSTGRES_USER: algoritmos_user
  #     POSTGRES_PASSWORD: algoritmos_pass
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

volumes:
  postgres_data: